# Project Euler: Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci = [1,1]
i = 1
evens = []
while(fibonacci[i-1]+fibonacci[i] < 4000000):
	fibonacci.append(fibonacci[i-1]+fibonacci[i])
	if (fibonacci[i-1]+fibonacci[i]) % 2 == 0:
		evens.append(fibonacci[i-1]+fibonacci[i])
	i += 1

print(sum(evens))